### ISSUE TITLE
Migrate to a pure Rust implementation for Falcon DSA

### ISSUE THREAD

**Issue by Al-Kindi-0** [0xPolygonMiden/crypto#281]
It seems that it would be beneficial for Miden wallet to migrate to a pure Rust implementation of Falcon DSA. Since we have a good portion of the code already in Rust, the task would then be to:

```[tasklist]
### Tasks
- [ ] Implement key generation algorithm.
- [ ] Implement the signing algorithm.
- [ ] Make the DSA generic over the hash-to-point algorithm.
```

**Comment by bobbinth** [comment]
Thank you! I would probably tackle the last two points first (i.e., signing algorithm and making the DSA generic over the hashing function), and would tackle the key generation in separate PR.

**Comment by bobbinth** [comment]
Closed by #285.
