### ISSUE TITLE
Tracking issue: Implement Merkle mountain range

### ISSUE THREAD

**Issue by grjte** [0xPolygonMiden/crypto#51]
### Goal
Implement Merkle mountain range in Rust and Miden Assembly.

### Details
The MMR is an append-only log used for the notes database, which stores all notes ever created. This data structure was chosen because notes can be easily added even if most nodes have been discarded. Additionally, inclusion witnesses never become stale (although they may need to be extended)

The MMR can also be used to track the history of the chain, as described here: https://github.com/0xPolygonMiden/miden-base/discussions/17

```[tasklist]
### Must have (Rust)
- [x] Add elements to a full tree (https://github.com/0xPolygonMiden/crypto/pull/67)
- [x] Generate an accumulator (https://github.com/0xPolygonMiden/crypto/pull/67)
- [x] Generate Merkle openings for a leaf (https://github.com/0xPolygonMiden/crypto/pull/67)
- [x] Verify Merkle openings (https://github.com/0xPolygonMiden/crypto/pull/67)
```
```[tasklist]
### Must have (Miden assembly)
- [x] Verify Merkle openings (https://github.com/0xPolygonMiden/miden-vm/pull/812)
- [x] Add an element using just the accumulator (https://github.com/0xPolygonMiden/miden-vm/pull/855)
- [x] Pack commitment (https://github.com/0xPolygonMiden/miden-vm/pull/841)
- [x] Unpack commitment (https://github.com/0xPolygonMiden/miden-vm/pull/834)
```
```[tasklist]
### Nice to have
- [x] Add an element using just the accumulator (https://github.com/0xPolygonMiden/crypto/pull/86)
- [x] Update an accumulator (https://github.com/0xPolygonMiden/crypto/pull/86)
```
```[tasklist]
### Non goals
- [x] Updating values (currently unnecessary)
```

## Working group:
@hackaugusto , @bobbinth, @Al-Kindi-0 
(Augusto to do the work, Bobbin & Al for discussion & review)

<details>
<summary>Workflow</summary>

- Discussion should happen here or in the related sub-issues.
- PRs should only be merged by the coordinator, to ensure everyone is able to review.
- Aim to complete reviews within 24 hours.
- When a related sub-issue is opened:
    - add it to the list of sub-issues in this tracking issue
- When opening a related PR:
    - request review from everyone in this working group
- When a sub-issue is completed:
    - close the related issue with a comment that links to the PR where the work was completed
</details>

### Coordinator: @hackaugusto 

<details>
<summary>Workflow</summary>

The working group coordinator ensures scope & progress tracking are transparent and accurate. They will:

- Merge approved PRs after all working group members have completed their reviews.
    - add the PR # to the relevant section of the current tracking PR.
    - close any completed sub-issue(s) with a comment that links to the PR where the work was completed
- Monitor workflow items and complete anything that slips through the cracks.
- Monitor scope to see if anything is untracked or unclear. Create missing sub-issues or initiate discussion as required.
- Monitor progress to see if there's anything which isn't moving forward. Initiate discussion as required.
- Identify PRs with especially significant changes and add @grjte and @bobbinth for review.
</details>

**Comment by bobbinth** [comment]
From Miden assembly standpoint, I think we need to expose just a few procedures to work with MMR. I'm thinking of the following:

* `std::collections::mmr::insert` - to insert a new node into the MMR.
* `std::collections::mmr::verify` - to verify that a node is in the MMR.
* `std::collections::mmr::pack` - computes a single 4-element commitment to the MMR.
* `std::collections::mmr::unpack` - inverts a single 4-element MMR commitment into the MMR.

Since MMR consists of a variable number of roots, we can't keep it all on the stack. My thinking is that we can keep the MMR roots in memory and represent MMR on the stack with 2 elements: memory pointer to the first root of MMR and memory pointer to the last root of MMR. There could be other ways of doing this too, but for now I assume that this is how we refer to the MMR.

### Insert
This procedure inserts a new node into the MMR. The stack transition could look as follows:
```
[n3, n2, n1, n0, first_ptr, last_ptr, ...] -> [first_ptr, last_ptr, ... ]
```
Where, `n0, ..., n3` are the elements representing the node to be inserted, and `first_ptr` and `last_ptr` specify the MMR.

### Verify
This procedure succeeds if the specified node is present in the MMR and fails otherwise. Stack transition could look as follows:
```
[n3, n2, n1, n0, first_ptr, last_ptr, ...] -> [n3, n2, n1, n0, first_ptr, last_ptr, ...]
```

### Pack
This procedure computes a single short commitment to the MMR. Stack transition could look as follows:
```
[first_ptr, last_ptr, ... ] -> [c3, c2, c1, c0, first_ptr, last_ptr, ...] 
```
Where, `c0, ..., c3` is the commitment to MMR computed using "bagging" algorithm described [here](https://docs.grin.mw/wiki/chain-state/merkle-mountain-range/) (or something similar).

### Unpack
This procedure inverts a single short commitment to MMR and writes MMR roots into memory. Stack transition could look as follows:
```
[c3, c2, c1, c0, ...] -> [first_ptr, last_ptr, ... ]
```

**Comment by bobbinth** [comment]
With the generic `MerkleStore`, supporting `verify` method will probably be quite difficult. So, I'm thinking we should replace it with `get` method (at least for now, and then we can figure out how to make `verify` work later). Specifically:

The method would be `std::collections::mmr::get` and the stack transition would be as follows:
```
[pos, first_ptr, last_ptr, ...] -> [n3, n2, n1, n0, first_ptr, last_ptr, ...]
```
Where `pos` is the absolute position of the leaf in the MMR and `[n0, n1, n2, n3]` is the value of the leaf.

Internally, the procedure would need to do the following things:
1. Convert `pos` to peak index and relative node index and tree depth (probably using algorithm from [here](https://github.com/0xPolygonMiden/crypto/blob/next/src/merkle/mmr/full.rs#L259)).
2. Load the relevant peak onto the stack from `first_ptr + peak_index`.
3. Use `mtree_get` to retrieve the relevant leaf from the the peak.
