### ISSUE TITLE
Tracking issue: Sparse Merkle tree implementations

### ISSUE THREAD

**Issue by bobbinth** [0xPolygonMiden/crypto#7]
### Goal
We should add implementations of Sparse Merkle tree. 

### Details
Specifically, I'm thinking of the following variants:

* Simple SMT (could go into `/merkle/simple_smt.rs` module).
* Compact SMT (could go into `/merkle/compact_smt.rs` module).

References: 
* https://github.com/0xPolygonMiden/miden-vm/issues/258
* https://github.com/0xPolygonMiden/miden-vm/pull/373

```[tasklist]
### MUST HAVE
- [x] #21 
- [x] #35
- [ ] #22
- [ ] https://github.com/0xPolygonMiden/miden-vm/issues/762
- [ ] https://github.com/0xPolygonMiden/miden-vm/issues/763
- [ ] https://github.com/0xPolygonMiden/crypto/issues/89
- [ ] #38
- [ ] #36
- [ ] #37
```

```[tasklist]
### NICE TO HAVE
```

## Working group:
@al-kindi-0, @bobbinth, @grjte, @vlopes11, @hackaugusto 

<details>
<summary>Workflow</summary>

- Discussion should happen here or in the related sub-issues.
- PRs should only be merged by the coordinator, to ensure everyone is able to review.
- Aim to complete reviews within 24 hours.
- When a related sub-issue is opened:
    - add it to the list of sub-issues in this tracking issue
- When opening a related PR:
    - request review from everyone in this working group
- When a sub-issue is completed:
    - close the related issue with a comment that links to the PR where the work was completed
</details>

### Coordinator: @vlopes11 

<details>
<summary>Workflow</summary>

The working group coordinator ensures scope & progress tracking are transparent and accurate. They will:

- Merge approved PRs after all working group members have completed their reviews.
    - add the PR # to the relevant section of the current tracking PR.
    - close any completed sub-issue(s) with a comment that links to the PR where the work was completed
- Monitor workflow items and complete anything that slips through the cracks.
- Monitor scope to see if anything is untracked or unclear. Create missing sub-issues or initiate discussion as required.
- Monitor progress to see if there's anything which isn't moving forward. Initiate discussion as required.
- Identify PRs with especially significant changes and add @grjte and @bobbinth for review.
</details>
